### ISSUE TITLE
Installation of resolvconf can collide with dns-resolver role

### ISSUE THREAD

**Issue by Carbenium** [SOSETH/network#1]
We install resolvconf in https://github.com/SOSETH/network/blob/master/tasks/main.yml#L9.
The dns-resolver role removes it again here: https://github.com/SOSETH/dns-resolver/blob/master/tasks/main.yml#L5

This can lead to installation/removal cycles if both roles are assigned to a host.

**Comment by uubk** [comment]
Should be fixed by https://github.com/SOSETH/dns-resolver/commit/870fb81ad2bb14bdf3f8fe85ee527dbea48fbcd3, right?

**Comment by Carbenium** [comment]
Yes, looks like it. Maybe we should then remove the ```resolvconf``` installation from this role?
Or maybe even merge the two roles?

**Comment by uubk** [comment]
Merging is probably not a good idea - `dns-resolver` is a separate role because you'd normally use your network's local DNS resolvers, except on e.g. mailservers where you want local resolution due to DNSSEC and DNSBL rate limits.
Therefore, we should probably leave `resolvconf` in here too.

**Comment by Carbenium** [comment]
> Should be fixed by [SOSETH/dns-resolver@870fb81](https://github.com/SOSETH/dns-resolver/commit/870fb81ad2bb14bdf3f8fe85ee527dbea48fbcd3), right?

:+1:
